### ISSUE TITLE
Hi, when i try to run it, it shows the error below

### ISSUE THREAD

**Issue by HoxtonR** [conceptofmind/LaMDA-pytorch#3]
Traceback (most recent call last):
  File "C:\Users\HoxtonR\Desktop\LaMDA\LaMDA-pytorch-main\test.py", line 1, in <module>
    from lamda_pytorch.lamda_pytorch import LaMDA
  File "C:\Users\HoxtonR\Desktop\LaMDA\LaMDA-pytorch-main\lamda_pytorch\__init__.py", line 1, in <module>
    from lamda_pytorch.lamda_pytorch import LaMDA
  File "C:\Users\HoxtonR\Desktop\LaMDA\LaMDA-pytorch-main\lamda_pytorch\lamda_pytorch.py", line 9, in <module>
    from config.config import CFG
ModuleNotFoundError: No module named 'config'

**Comment by conceptofmind** [comment]
Hi @HoxtonR ,

I just pushed an update to fix the import errors you had listed. One of the last updates had changed the file directory structure. 

The repository initially consisted of just the pre-training architecture for the model but I am actively updating it on a daily basis to include a full pre-training example. The training script is not fully implemented as a tokenizer needs to still be provided and the package manager needs to be implemented since this model requires specific libraries for scaling.

I will be updating consistently and keep this issue open for now.

Best,

Enrico
